package com.hmc.entity;
// Generated Jul 11, 2022 1:50:54 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "bookstore")
public class Cart implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private User user;
	private Set<CartBook> cartBooks = new HashSet<CartBook>(0);

	public Cart() {
	}

	public Cart(User user) {
		this.user = user;
	}

	public Cart(User user, Set<CartBook> cartBooks) {
		this.user = user;
		this.cartBooks = cartBooks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
	public Set<CartBook> getCartBooks() {
		return this.cartBooks;
	}

	public void setCartBooks(Set<CartBook> cartBooks) {
		this.cartBooks = cartBooks;
	}

}
